#!/bin/bash
# Copyright (C) 2000,2017 by Massimiliano Ghilardi
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
#

FIRSTARG=1
MODE=normal
DPY=

#echo "ntwstart: $# arguments [$@]"

for ARG
do
  #echo "ntwstart: now parsing [$ARG]"
  if [ "$FIRSTARG" = 1 ]; then
    set --
    FIRSTARG=0
  fi
  if [ "$MODE" = normal ]; then
    case "$ARG" in
      -h|--help|-help )
        echo "Usage: ntwstart [OPTIONS]
Attach a running twin server to a display or start a new server.
If a twin server is found, \`ntwdisplay' is used to attach it to a display,
else a new twin server is started.

Currently known options:

 -h, --help            show this help and exit
 --twin@<TWDISPLAY>    specify server to contact instead of autodetecting it
 <TWDISPLAY>           shortcut for --twin@<TWDISPLAY>
 --                    end of options: pass further args to ntwin or ntwdisplay
 --<OPTION>            other options are passed verbatim to ntwin or ntwdisplay
"
        exit 0
        ;;
      -- )
        # end of ntwstart options, pass the rest to ntwin or ntwdisplay
        MODE=literal
        ;;
      --twin@* )
        DPY="${ARG:7}";
        ;;
      -twin@* )
        DPY="${ARG:6}";
        ;;
      --*|-* )
        # accumulate current argument
        set -- "$@" "$ARG"
        ;;
      *:[0-9a-fA-F]* )
        DPY="$ARG";
        ;;
      * )
        echo "ntwstart: unknown option \`$ARG\'
try \`ntwstart --help\' for usage summary."
        exit 1
        ;;
    esac
  else
    # accumulate current argument
    set -- "$@" "$ARG"
  fi
  #echo "ntwstart: accumulated arguments [$@]"
done

if [ "$DPY" ]; then
  DPY="`ntwfindtwin \"$DPY\"`"
else
  DPY="`ntwfindtwin`"
fi

if [ "$DPY" ]; then
  echo "ntwstart: detected twin running on $DPY"
  exec ntwdisplay --twin@"$DPY" "$@"
else
  exec ntwin "$@"
fi
